# Generated by Django 4.2 on 2023-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('title', models.CharField(max_length=100)),
                ('dis', models.CharField(max_length=100)),
            ],
        ),
    ]
