# Generated by Django 4.2 on 2023-04-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='bookingdate',
        ),
    ]
