# Generated by Django 3.2.13 on 2023-07-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0004_rename_date_booking_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
